on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: goatg33k/fivem-lualint:dev
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    container:
      image: evandarwin/lua:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: docker://evandarwin/lua:latest
        with:
          args: |
            /bin/sh -c " \
            apk add nodejs yarn && yarn && \
            node -r ts-node/register ./generate-rc.ts && \
            luarocks install luacheck && \
            luacheck --config /github/workspace/.luacheckrc.default -t /github/workspace/tests"
